stages:
    - build
    - test
    - deploy

variables:
    IDF_REPO: ${GITLAB_SSH_SERVER}/idf/esp-idf.git

.add_gh_key_remote: &add_gh_key_remote |
    cit_add_ssh_key "${GH_PUSH_KEY}"
    git remote remove github || true
    git remote add github ${GH_PUSH_REPO}

before_script:
    # Use CI Tools
    - curl -sSL ${CIT_LOADER_URL} | sh
    - source citools/import_functions
    # Add gitlab ssh key
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY > ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - PATH=$CI_PROJECT_DIR/esp-idf/tools:$PATH
    - export MQTT_PATH=$CI_PROJECT_DIR

.build_template:
    stage: build
    tags:
        - build
        - internet
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    variables:
        IDF_CCACHE_ENABLE: "1"
    artifacts:
        paths:
            - "app_info_*.txt"
        reports:
            junit: "build_summary_*.xml"
        when: always
        expire_in: 1 week
    script:
        - cd $IDF_PATH && bash install.sh --enable-ci && cd $MQTT_PATH
        - rm -rf $IDF_PATH/components/mqtt/esp-mqtt && cp -r $MQTT_PATH $IDF_PATH/components/mqtt/
        - cd $IDF_PATH
        - >-
            idf-build-apps build --build-system cmake --no-check-warnings
            --junitxml $MQTT_PATH/build_summary_mqtt.xml
            --collect-app-info $MQTT_PATH/app_info_mqtt.txt
            -p examples/protocols --modified-components mqtt

build_idf_v5.5:
    extends: .build_template
    image: espressif/idf:release-v5.5

build_and_host_test:
    stage: build
    image: espressif/idf:release-v5.5
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    script:
        # Replace the IDF's default esp-mqtt with this version
        - rm -rf $IDF_PATH/components/mqtt/esp-mqtt && cp -r $MQTT_PATH $IDF_PATH/components/mqtt/
        - cd $IDF_PATH/components/mqtt/esp-mqtt/host_test
        - idf.py build
        - build/host_mqtt_client_test.elf

push_to_github:
    stage: deploy
    image: ${CI_DOCKER_REGISTRY}/esp32-ci-env
    tags:
        - build
    rules:
        - if: $CI_COMMIT_REF_NAME == "release/v5.5"
    when: on_success
    variables:
        GIT_STRATEGY: clone
    script:
        - *add_gh_key_remote
        - git push github HEAD:${CI_COMMIT_REF_NAME}
