# Note: No need to run build and test on master branch since we use FastForward merge strategy and so each merge request
# is tested and then merged onto top of master branch.
include:
    - component: $CI_SERVER_FQDN/ci/actions/idf-dynamic-pipeline/ci-component@main
      rules:
          - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      inputs:
          build-job-image: "espressif/idf:latest"
          test-job-image: "$CI_DOCKER_REGISTRY/target-test-env-v6.0:2"
          build-job-tags: ["brew", "build"]
          job-suffix: ":idf-v6.0"
    - component: $CI_SERVER_FQDN/ci/actions/idf-dynamic-pipeline/ci-component@main
      rules:
          - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      inputs:
          build-job-image: "espressif/idf:release-v5.5"
          test-job-image: "$CI_DOCKER_REGISTRY/target-test-env-v5.5:2"
          build-job-tags: ["brew", "build"]
          job-suffix: ":idf-v5.5"
    - component: $CI_SERVER_FQDN/ci/actions/idf-dynamic-pipeline/ci-component@main
      rules:
          - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      inputs:
          build-job-image: "espressif/idf:release-v5.4"
          test-job-image: "$CI_DOCKER_REGISTRY/target-test-env-v5.4:2"
          build-job-tags: ["brew", "build"]
          job-suffix: ":idf-v5.4"
    - component: $CI_SERVER_FQDN/ci/actions/idf-dynamic-pipeline/ci-component@main
      rules:
          - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      inputs:
          build-job-image: "espressif/idf:release-v5.3"
          test-job-image: "$CI_DOCKER_REGISTRY/target-test-env-v5.3:1"
          build-job-tags: ["brew", "build"]
          job-suffix: ":idf-v5.3"
